name: dbt CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  dbt:
    runs-on: ubuntu-latest
    env:
      DBT_PROFILES_DIR: ./
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dbt deps
        run: |
          python -m pip install --upgrade pip
          pip install dbt-postgres==1.10.11
          pip install -r requirements.txt || true

      - name: Install deps from packages.yml
        run: dbt deps

      - name: dbt parse
        run: dbt parse

      - name: dbt compile
        run: dbt compile

      - name: dbt test
        run: dbt test --profiles-dir ./
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_SCHEMA: ${{ secrets.DB_SCHEMA }}
