name: dbt CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  dbt:
    runs-on: ubuntu-latest
    env:
      DBT_PROFILES_DIR: ./
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dbt deps
        run: |
          python -m pip install --upgrade pip
          pip install dbt-postgres==1.10.11
          pip install -r requirements.txt || true

      - name: Run dbt wrapper script (PowerShell)
        shell: pwsh
        run: |
          $env:DB_HOST = '${{ secrets.DB_HOST }}'
          $env:DB_USER = '${{ secrets.DB_USER }}'
          $env:DB_PASS = '${{ secrets.DB_PASS }}'
          $env:DB_PORT = '${{ secrets.DB_PORT }}'
          $env:DB_NAME = '${{ secrets.DB_NAME }}'
          $env:DB_SCHEMA = '${{ secrets.DB_SCHEMA }}'
          pwsh ./scripts/run-dbt-ci.ps1
